/**
 * 8-bit Ripple Carry Adder with Overflow Detection
 *
 * Generated by XylonStudio Design Dragon
 * Description: Simple 8-bit adder demonstrating basic RTL generation
 */

module adder_8bit (
    input  [7:0] a,
    input  [7:0] b,
    input        cin,
    output [7:0] sum,
    output       cout,
    output       overflow
);

    // Internal signals
    wire [8:0] full_sum;

    // Addition with carry
    assign full_sum = {1'b0, a} + {1'b0, b} + {8'b0, cin};

    // Output assignments
    assign sum  = full_sum[7:0];
    assign cout = full_sum[8];

    // Overflow detection (for signed arithmetic)
    assign overflow = (a[7] == b[7]) && (sum[7] != a[7]);

endmodule
