/**
 * RISC-V ALU (32-bit)
 *
 * Generated by XylonStudio Design Dragon
 * Description: Integer ALU supporting RV32I base instructions
 */

module riscv_alu (
    input  [31:0] operand_a,
    input  [31:0] operand_b,
    input  [3:0]  alu_op,
    output [31:0] result,
    output        zero,
    output        negative
);

    // ALU operation codes
    localparam OP_ADD  = 4'b0000;
    localparam OP_SUB  = 4'b0001;
    localparam OP_AND  = 4'b0010;
    localparam OP_OR   = 4'b0011;
    localparam OP_XOR  = 4'b0100;
    localparam OP_SLL  = 4'b0101;  // Shift left logical
    localparam OP_SRL  = 4'b0110;  // Shift right logical
    localparam OP_SRA  = 4'b0111;  // Shift right arithmetic
    localparam OP_SLT  = 4'b1000;  // Set less than (signed)
    localparam OP_SLTU = 4'b1001;  // Set less than unsigned

    // Internal signals
    reg [31:0] alu_result;
    wire signed [31:0] signed_a = operand_a;
    wire signed [31:0] signed_b = operand_b;

    // ALU operation
    always @(*) begin
        case (alu_op)
            OP_ADD:  alu_result = operand_a + operand_b;
            OP_SUB:  alu_result = operand_a - operand_b;
            OP_AND:  alu_result = operand_a & operand_b;
            OP_OR:   alu_result = operand_a | operand_b;
            OP_XOR:  alu_result = operand_a ^ operand_b;
            OP_SLL:  alu_result = operand_a << operand_b[4:0];
            OP_SRL:  alu_result = operand_a >> operand_b[4:0];
            OP_SRA:  alu_result = signed_a >>> operand_b[4:0];
            OP_SLT:  alu_result = (signed_a < signed_b) ? 32'b1 : 32'b0;
            OP_SLTU: alu_result = (operand_a < operand_b) ? 32'b1 : 32'b0;
            default: alu_result = 32'b0;
        endcase
    end

    // Output assignments
    assign result   = alu_result;
    assign zero     = (alu_result == 32'b0);
    assign negative = alu_result[31];

endmodule
