/**
 * 16-bit Barrel Shifter
 *
 * Generated by XylonStudio Design Dragon
 * Description: Logarithmic barrel shifter with multi-directional shift
 */

module barrel_shifter_16bit (
    input  [15:0] data_in,
    input  [3:0]  shift_amount,
    input  [1:0]  shift_dir,    // 00=left, 01=right, 10=rotate_left, 11=rotate_right
    output [15:0] data_out
);

    // Internal shift stages
    wire [15:0] stage0, stage1, stage2, stage3;

    // Stage 0: Shift by 1 if shift_amount[0] == 1
    assign stage0 = shift_amount[0] ?
                    (shift_dir == 2'b00 ? {data_in[14:0], 1'b0} :           // Left
                     shift_dir == 2'b01 ? {1'b0, data_in[15:1]} :           // Right
                     shift_dir == 2'b10 ? {data_in[14:0], data_in[15]} :    // Rotate left
                                          {data_in[0], data_in[15:1]}) :    // Rotate right
                    data_in;

    // Stage 1: Shift by 2 if shift_amount[1] == 1
    assign stage1 = shift_amount[1] ?
                    (shift_dir == 2'b00 ? {stage0[13:0], 2'b0} :
                     shift_dir == 2'b01 ? {2'b0, stage0[15:2]} :
                     shift_dir == 2'b10 ? {stage0[13:0], stage0[15:14]} :
                                          {stage0[1:0], stage0[15:2]}) :
                    stage0;

    // Stage 2: Shift by 4 if shift_amount[2] == 1
    assign stage2 = shift_amount[2] ?
                    (shift_dir == 2'b00 ? {stage1[11:0], 4'b0} :
                     shift_dir == 2'b01 ? {4'b0, stage1[15:4]} :
                     shift_dir == 2'b10 ? {stage1[11:0], stage1[15:12]} :
                                          {stage1[3:0], stage1[15:4]}) :
                    stage1;

    // Stage 3: Shift by 8 if shift_amount[3] == 1
    assign stage3 = shift_amount[3] ?
                    (shift_dir == 2'b00 ? {stage2[7:0], 8'b0} :
                     shift_dir == 2'b01 ? {8'b0, stage2[15:8]} :
                     shift_dir == 2'b10 ? {stage2[7:0], stage2[15:8]} :
                                          {stage2[7:0], stage2[15:8]}) :
                    stage2;

    // Output
    assign data_out = stage3;

endmodule
